CREATE TABLE
IF NOT EXISTS `t_data_source` (
	`id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`data_source_name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '数据源名称',
	`driver_class_name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'jdbc驱动类名',
	`ip` VARCHAR (100) NOT NULL DEFAULT '' COMMENT 'ip或域名',
	`database` VARCHAR (20) NOT NULL DEFAULT '' COMMENT '数据库',
	`user_name` VARCHAR (100) NOT NULL DEFAULT '' COMMENT '用户名',
	`password` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '密码',
	`data_status` TINYINT (4) NOT NULL DEFAULT '1' COMMENT '0:禁用,1:启用,2:已删除',
	`create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '数据库源';

CREATE TABLE
IF NOT EXISTS `t_template` (
	`id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`template_name` VARCHAR (100) NOT NULL DEFAULT '' COMMENT '模板名',
	`context` VARCHAR (5000) NOT NULL DEFAULT '' COMMENT '模板内容',
	`author` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '作者',
	`table_prefix` VARCHAR (20) NOT NULL DEFAULT '' COMMENT '表前缀',
	`template_type` TINYINT (4) NOT NULL DEFAULT 0 COMMENT '0:java,1:xml,2:html',
	`package_path` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '生成包名',
	`file_path` VARCHAR (200) NOT NULL DEFAULT '' COMMENT '生成的文件路径',
	`data_status` TINYINT (4) NOT NULL DEFAULT 1 COMMENT '0:禁用,1:启用,2:已删除',
	`create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '模板';